### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by rbarghou** [maxwells/snake#3]
Got this error on launch
Would be happy to retry

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [snake](https://github.com/maxwells/snake) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/ramseybarghouti/.atom/packages/snake/lib/snake-view.coffee:5

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/ramseybarghouti/.atom/packages/snake/lib/snake-view.coffee:5:199)
  at /Users/ramseybarghouti/.atom/packages/snake/lib/snake-view.coffee:6:3
  at Object.<anonymous> (/Users/ramseybarghouti/.atom/packages/snake/lib/snake-view.coffee:145:5)
  at Object.<anonymous> (/Users/ramseybarghouti/.atom/packages/snake/lib/snake-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ramseybarghouti/.atom/packages/snake/lib/snake.coffee:1:13)
  at Object.<anonymous> (/Users/ramseybarghouti/.atom/packages/snake/lib/snake.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:256:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:261:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:306:24)
  at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:260:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -1:42.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:40.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.1
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0

# Dev
No dev packages
```

**Comment by rbarghou** [comment]
Closed do to inactivity.
