### ISSUE TITLE
Failed to load the snake package

### ISSUE THREAD

**Issue by nashley** [maxwells/snake#5]
[Enter steps to reproduce below:]
1. Try to install the package

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [snake](https://github.com/maxwells/snake) package, v0.2.0
### Stack Trace

Failed to load the snake package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\Nick\.atom\packages\snake\lib\snake-view.coffee:1:1)
  at C:\Users\Nick\.atom\packages\snake\lib\snake-view.coffee:6:3
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\snake\lib\snake-view.coffee:145:5)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\snake\lib\snake-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\snake\lib\snake.coffee:1:13)
  at Object.<anonymous> (C:\Users\Nick\.atom\packages\snake\lib\snake.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:473:30)
  at C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\Nick\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -5:30.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:54.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:53.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:53.5.0 application:open-file (atom-text-editor.editor.is-focused)
     -2:51.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  8x -2:51.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "steam-pirate-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
css-snippets, v0.9.0
linter-gcc, v0.3.9
snake, v0.2.0
steam-pirate-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by embasoft** [comment]
Change the value of "main" in package.json from "./lib/atom-2048" to "./atom-2048" to fix the error.

**Comment by embasoft** [comment]
Oh my solution is wrong of course, I mean "./lib/snake" to ". /snake" :D

**Comment by ghost** [comment]
I too have this issue. Are you able to push out a fix that fixes this issue?
Although I can do it manually, it does become quite an inconvenience, and I'm sure it deters many.

**Comment by Cxarli** [comment]
I just submitted a PR for this, hope it'll get pulled soon
